# OCPI 2.3.0 - CDRs Module
# Sender (CPO) and Receiver (eMSP) interfaces for Charge Detail Records
openapi: 3.1.0
info:
  title: OCPI 2.3.0 - CDRs
  description: >-
    The CDRs module provides Charge Detail Records (CDRs) which describe completed
    charging sessions. Data owner is typically the CPO.
  version: 2.3.0
  license:
    name: Creative Commons Attribution-NoDerivatives 4.0 International
    url: https://creativecommons.org/licenses/by-nd/4.0/

externalDocs:
  description: OCPI 2.3.0 Specification
  url: https://github.com/ocpi/ocpi

servers:
  - url: https://example.com/ocpi/2.3.0
    description: Example OCPI server

security:
  - TokenAuth: []

paths:
  # ---- Sender Interface (CPO) ----

  /cdrs:
    get:
      operationId: getCdrs
      summary: Get CDRs List (Sender)
      description: >-
        Fetch CDR objects from the CPO, last updated between date_from and date_to (paginated).
      tags:
        - CDRs - Sender
      parameters:
        - $ref: './shared/headers.yaml#/components/parameters/Authorization'
        - $ref: './shared/headers.yaml#/components/parameters/X-Request-ID'
        - $ref: './shared/headers.yaml#/components/parameters/X-Correlation-ID'
        - $ref: './shared/headers.yaml#/components/parameters/OCPI-from-country-code'
        - $ref: './shared/headers.yaml#/components/parameters/OCPI-from-party-id'
        - $ref: './shared/headers.yaml#/components/parameters/OCPI-to-country-code'
        - $ref: './shared/headers.yaml#/components/parameters/OCPI-to-party-id'
        - $ref: './shared/parameters.yaml#/components/parameters/date_from'
        - $ref: './shared/parameters.yaml#/components/parameters/date_to'
        - $ref: './shared/parameters.yaml#/components/parameters/offset'
        - $ref: './shared/parameters.yaml#/components/parameters/limit'
      responses:
        '200':
          description: List of CDR objects.
          headers:
            X-Total-Count:
              $ref: './shared/headers.yaml#/components/headers/X-Total-Count'
            X-Limit:
              $ref: './shared/headers.yaml#/components/headers/X-Limit'
            Link:
              $ref: './shared/headers.yaml#/components/headers/Link'
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './shared/common.yaml#/components/schemas/OcpiResponse'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/CDR'
        '401':
          description: Unauthorized.

    # ---- Receiver Interface (eMSP) ----

    post:
      operationId: postReceiverCdr
      summary: Create CDR (Receiver)
      description: >-
        Create a new CDR in the eMSP's system. The response SHALL contain a Location header
        with the URL to the newly created CDR.
      tags:
        - CDRs - Receiver
      parameters:
        - $ref: './shared/headers.yaml#/components/parameters/Authorization'
        - $ref: './shared/headers.yaml#/components/parameters/X-Request-ID'
        - $ref: './shared/headers.yaml#/components/parameters/X-Correlation-ID'
        - $ref: './shared/headers.yaml#/components/parameters/OCPI-from-country-code'
        - $ref: './shared/headers.yaml#/components/parameters/OCPI-from-party-id'
        - $ref: './shared/headers.yaml#/components/parameters/OCPI-to-country-code'
        - $ref: './shared/headers.yaml#/components/parameters/OCPI-to-party-id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CDR'
      responses:
        '201':
          description: CDR created. Location header contains URL to the new CDR.
          headers:
            Location:
              description: URL to the newly created CDR object.
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: './shared/common.yaml#/components/schemas/OcpiResponse'
        '401':
          description: Unauthorized.

  /cdrs/{cdr_id}:
    get:
      operationId: getReceiverCdr
      summary: Get CDR (Receiver)
      description: >-
        Retrieve an existing CDR from the eMSP's system. The URL is provided
        by the eMSP in the Location header of the POST response.
      tags:
        - CDRs - Receiver
      parameters:
        - $ref: './shared/headers.yaml#/components/parameters/Authorization'
        - $ref: './shared/headers.yaml#/components/parameters/X-Request-ID'
        - $ref: './shared/headers.yaml#/components/parameters/X-Correlation-ID'
        - $ref: './shared/headers.yaml#/components/parameters/OCPI-from-country-code'
        - $ref: './shared/headers.yaml#/components/parameters/OCPI-from-party-id'
        - $ref: './shared/headers.yaml#/components/parameters/OCPI-to-country-code'
        - $ref: './shared/headers.yaml#/components/parameters/OCPI-to-party-id'
        - name: cdr_id
          in: path
          required: true
          description: ID of the CDR (as returned in the Location header).
          schema:
            type: string
      responses:
        '200':
          description: The requested CDR object.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './shared/common.yaml#/components/schemas/OcpiResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/CDR'
        '401':
          description: Unauthorized.
        '404':
          description: CDR not found.

components:
  securitySchemes:
    TokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: OCPI credentials token passed in the Authorization header.
  schemas:
    CDR:
      type: object
      description: >-
        A Charge Detail Record is the description of a concluded charging session.
        CDRs are immutable once sent; use Credit CDRs for corrections.
      required:
        - country_code
        - party_id
        - id
        - start_date_time
        - end_date_time
        - cdr_token
        - auth_method
        - cdr_location
        - currency
        - charging_periods
        - total_cost
        - total_energy
        - total_time
        - last_updated
      properties:
        country_code:
          type: string
          maxLength: 2
          description: ISO-3166 alpha-2 country code of the CPO.
        party_id:
          type: string
          maxLength: 3
          description: ID of the CPO.
        id:
          type: string
          maxLength: 39
          description: Unique ID of the CDR per country_code/party_id combination.
        start_date_time:
          $ref: './shared/common.yaml#/components/schemas/DateTime'
        end_date_time:
          $ref: './shared/common.yaml#/components/schemas/DateTime'
        session_id:
          type: string
          maxLength: 36
          description: Unique ID of the Session for which this CDR is sent.
        cdr_token:
          $ref: '#/components/schemas/CdrToken'
        auth_method:
          $ref: '#/components/schemas/AuthMethod'
        authorization_reference:
          type: string
          maxLength: 36
          description: Reference to the authorization given by the eMSP.
        cdr_location:
          $ref: '#/components/schemas/CdrLocation'
        meter_id:
          type: string
          maxLength: 255
          description: Identification of the Meter inside the Charge Point.
        currency:
          type: string
          maxLength: 3
          description: ISO-4217 code of the currency.
        tariffs:
          type: array
          items:
            $ref: './tariffs.yaml#/components/schemas/Tariff'
          description: List of relevant Tariffs.
        charging_periods:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/ChargingPeriod'
          description: List of Charging Periods that make up this charging session.
        signed_data:
          $ref: '#/components/schemas/SignedData'
        total_cost:
          $ref: './shared/common.yaml#/components/schemas/Price'
        total_fixed_cost:
          $ref: './shared/common.yaml#/components/schemas/Price'
        total_energy:
          type: number
          description: Total energy charged in kWh.
        total_energy_cost:
          $ref: './shared/common.yaml#/components/schemas/Price'
        total_time:
          type: number
          description: Total duration of the charging session in hours.
        total_time_cost:
          $ref: './shared/common.yaml#/components/schemas/Price'
        total_parking_time:
          type: number
          description: Total duration of not charging in hours.
        total_parking_cost:
          $ref: './shared/common.yaml#/components/schemas/Price'
        total_reservation_cost:
          $ref: './shared/common.yaml#/components/schemas/Price'
        remark:
          type: string
          maxLength: 255
          description: Optional remark with additional information.
        invoice_reference_id:
          type: string
          maxLength: 39
          description: Reference to an invoice for this CDR.
        credit:
          type: boolean
          description: When true, this is a Credit CDR correcting a previous CDR.
        credit_reference_id:
          type: string
          maxLength: 39
          description: ID of the CDR that this Credit CDR corrects.
        home_charging_compensation:
          type: boolean
          description: When true, this CDR is for a home charger session with financial compensation.
        last_updated:
          $ref: './shared/common.yaml#/components/schemas/DateTime'
      additionalProperties: true

    CdrToken:
      type: object
      description: Identifies the token used to start a charging session in a CDR.
      required:
        - country_code
        - party_id
        - uid
        - type
        - contract_id
      properties:
        country_code:
          type: string
          maxLength: 2
          description: ISO-3166 alpha-2 country code of the eMSP that owns this Token.
        party_id:
          type: string
          maxLength: 3
          description: ID of the eMSP that owns this Token.
        uid:
          type: string
          maxLength: 36
          description: Unique ID by which this Token can be identified.
        type:
          $ref: './tokens.yaml#/components/schemas/TokenType'
        contract_id:
          type: string
          maxLength: 36
          description: Uniquely identifies the EV driver contract token within the eMSP's platform.
      additionalProperties: true

    CdrLocation:
      type: object
      description: Snapshot of the Location where the charging session took place.
      required:
        - id
        - address
        - city
        - country
        - coordinates
        - evse_uid
        - evse_id
        - connector_id
        - connector_standard
        - connector_format
        - connector_power_type
      properties:
        id:
          type: string
          maxLength: 36
          description: Uniquely identifies the Location within the CPO's platform.
        name:
          type: string
          maxLength: 255
          description: Display name of the location.
        address:
          type: string
          maxLength: 45
          description: Street/block name and house number.
        city:
          type: string
          maxLength: 45
          description: City or town.
        postal_code:
          type: string
          maxLength: 10
          description: Postal code.
        state:
          type: string
          maxLength: 20
          description: State or province.
        country:
          type: string
          maxLength: 3
          description: ISO 3166-1 alpha-3 country code.
        coordinates:
          $ref: './shared/common.yaml#/components/schemas/GeoLocation'
        evse_uid:
          type: string
          maxLength: 36
          description: Uniquely identifies the EVSE within the CPO's platform.
        evse_id:
          type: string
          maxLength: 48
          description: Compliant with eMA ID specification.
        connector_id:
          type: string
          maxLength: 36
          description: Identifier of the connector within the EVSE.
        connector_standard:
          $ref: './locations.yaml#/components/schemas/ConnectorType'
        connector_format:
          $ref: './locations.yaml#/components/schemas/ConnectorFormat'
        connector_power_type:
          $ref: './locations.yaml#/components/schemas/PowerType'
      additionalProperties: true

    ChargingPeriod:
      type: object
      description: >-
        A Charging Period is a group of values for a period of time during a charging session.
        A new period SHOULD be added every time a Price Component becomes active.
      required:
        - start_date_time
        - dimensions
      properties:
        start_date_time:
          $ref: './shared/common.yaml#/components/schemas/DateTime'
        dimensions:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/CdrDimension'
          description: List of relevant values for this charging period.
        tariff_id:
          type: string
          maxLength: 36
          description: Unique identifier of the Tariff relevant for this Charging Period.
      additionalProperties: true

    CdrDimension:
      type: object
      description: A measured dimension value for a charging period.
      required:
        - type
        - volume
      properties:
        type:
          $ref: '#/components/schemas/CdrDimensionType'
        volume:
          type: number
          description: Volume of the dimension consumed.
      additionalProperties: true

    SignedData:
      type: object
      description: Signed meter data for transparency and verification.
      required:
        - encoding_method
        - signed_values
      properties:
        encoding_method:
          type: string
          maxLength: 36
          description: The name of the encoding used in the SignedData field.
        encoding_method_version:
          type: integer
          description: Version of the EncodingMethod.
        public_key:
          type: string
          maxLength: 512
          description: Public key used to sign the data, base64 encoded.
        signed_values:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/SignedValue'
          description: One or more signed values.
        url:
          type: string
          maxLength: 512
          description: URL to verify the signed data.
      additionalProperties: true

    SignedValue:
      type: object
      description: A single signed meter value.
      required:
        - nature
        - plain_data
        - signed_data
      properties:
        nature:
          type: string
          maxLength: 32
          description: "Nature of the value: Start, End, Intermediate, or other."
        plain_data:
          type: string
          maxLength: 512
          description: The un-encoded string of data.
        signed_data:
          type: string
          maxLength: 5000
          description: Blob of signed data, base64 encoded.
      additionalProperties: true

    # ---- Enums ----

    AuthMethod:
      type: string
      enum:
        - AUTH_REQUEST
        - COMMAND
        - WHITELIST
      description: Method used to authenticate a charging session.

    CdrDimensionType:
      type: string
      enum:
        - CURRENT
        - ENERGY
        - ENERGY_EXPORT
        - ENERGY_IMPORT
        - MAX_CURRENT
        - MIN_CURRENT
        - MAX_POWER
        - MIN_POWER
        - PARKING_TIME
        - POWER
        - RESERVATION_TIME
        - STATE_OF_CHARGE
        - TIME
      description: Types of CDR dimensions.
