# OCPI 2.3.0 - Credentials Module
# Registration, credential exchange, and unregistration
openapi: 3.1.0
info:
  title: OCPI 2.3.0 - Credentials
  description: >-
    The credentials module is used to exchange the credentials token that has to be used
    by parties for authorization of requests. This module is symmetric: every implementation
    needs to be able to call and handle requests to this module.
  version: 2.3.0
  license:
    name: Creative Commons Attribution-NoDerivatives 4.0 International
    url: https://creativecommons.org/licenses/by-nd/4.0/

externalDocs:
  description: OCPI 2.3.0 Specification
  url: https://github.com/ocpi/ocpi

servers:
  - url: https://example.com/ocpi/2.3.0
    description: Example OCPI server

security:
  - TokenAuth: []

paths:
  /credentials:
    get:
      operationId: getCredentials
      summary: Get Credentials
      description: >-
        Retrieves the credentials object to access the server's platform.
        The response contains the credentials object with business details.
      tags:
        - Credentials
      parameters:
        - $ref: './shared/headers.yaml#/components/parameters/Authorization'
        - $ref: './shared/headers.yaml#/components/parameters/X-Request-ID'
        - $ref: './shared/headers.yaml#/components/parameters/X-Correlation-ID'
      responses:
        '200':
          description: The credentials to access this platform.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './shared/common.yaml#/components/schemas/OcpiResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/Credentials'
        '401':
          description: Unauthorized - Missing or invalid credentials token.

    post:
      operationId: postCredentials
      summary: Register (Credentials Exchange)
      description: >-
        Provides the server with credentials to access the client's system (registration).
        If successful, the server generates a new credentials token and responds with the
        client's new credentials to access the server's system.
        Returns HTTP 405 if the client has already been registered.
      tags:
        - Credentials
      parameters:
        - $ref: './shared/headers.yaml#/components/parameters/Authorization'
        - $ref: './shared/headers.yaml#/components/parameters/X-Request-ID'
        - $ref: './shared/headers.yaml#/components/parameters/X-Correlation-ID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        '200':
          description: Registration successful. Contains new credentials to access the server.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './shared/common.yaml#/components/schemas/OcpiResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/Credentials'
        '401':
          description: Unauthorized - Missing or invalid credentials token.
        '405':
          description: Method not allowed - Client has already been registered.

    put:
      operationId: putCredentials
      summary: Update Credentials
      description: >-
        Provides the server with updated credentials to access the client's system.
        A PUT will switch to the version that contains this credentials endpoint if different.
        The server must fetch the client's endpoints again.
        Returns HTTP 405 if the client has not been registered yet.
      tags:
        - Credentials
      parameters:
        - $ref: './shared/headers.yaml#/components/parameters/Authorization'
        - $ref: './shared/headers.yaml#/components/parameters/X-Request-ID'
        - $ref: './shared/headers.yaml#/components/parameters/X-Correlation-ID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        '200':
          description: Credentials updated. Contains new credentials to access the server.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './shared/common.yaml#/components/schemas/OcpiResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/Credentials'
        '401':
          description: Unauthorized - Missing or invalid credentials token.
        '405':
          description: Method not allowed - Client has not been registered yet.

    delete:
      operationId: deleteCredentials
      summary: Unregister
      description: >-
        Informs the server that its credentials to access the client's system are now invalid.
        Both parties must end any automated communication.
        Returns HTTP 405 if the client has not been registered.
      tags:
        - Credentials
      parameters:
        - $ref: './shared/headers.yaml#/components/parameters/Authorization'
        - $ref: './shared/headers.yaml#/components/parameters/X-Request-ID'
        - $ref: './shared/headers.yaml#/components/parameters/X-Correlation-ID'
      responses:
        '200':
          description: Unregistration successful.
          content:
            application/json:
              schema:
                $ref: './shared/common.yaml#/components/schemas/OcpiResponse'
        '401':
          description: Unauthorized - Missing or invalid credentials token.
        '405':
          description: Method not allowed - Client has not been registered.

components:
  securitySchemes:
    TokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: OCPI credentials token passed in the Authorization header.
  schemas:
    Credentials:
      type: object
      description: >-
        Credentials object containing the token, version URL, and roles for a platform.
      required:
        - token
        - url
        - roles
      properties:
        token:
          type: string
          maxLength: 64
          description: >-
            The credentials token for the other party to authenticate in your system.
            Should only contain printable non-whitespace ASCII characters (U+0021 to U+007E).
        url:
          type: string
          format: uri
          maxLength: 255
          description: The URL to your API versions endpoint.
        hub_party_id:
          type: string
          maxLength: 5
          description: >-
            The Hub party of this platform. The two-letter country code and three-character
            party ID are concatenated together as one five-character string.
        roles:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/CredentialsRole'
          description: List of the roles this platform provides.
      additionalProperties: true

    CredentialsRole:
      type: object
      description: Role information for a platform during credentials exchange.
      required:
        - role
        - business_details
        - party_id
        - country_code
      properties:
        role:
          $ref: './shared/common.yaml#/components/schemas/Role'
        business_details:
          $ref: './shared/common.yaml#/components/schemas/BusinessDetails'
        party_id:
          type: string
          maxLength: 3
          description: CPO, eMSP (or other role) ID of this party (following the ISO-15118 standard).
        country_code:
          type: string
          maxLength: 2
          description: ISO-3166 alpha-2 country code of the country this party is operating in.
      additionalProperties: true
