openapi: 3.1.0
info:
  title: OCPI 2.1.1 - CDRs
  description: The CDRs module provides Charge Detail Records (CDRs) which
    describe completed charging sessions. Data owner is typically the CPO.
  version: 2.1.1
  license:
    name: Creative Commons Attribution-NoDerivatives 4.0 International
    url: https://creativecommons.org/licenses/by-nd/4.0/
externalDocs:
  description: OCPI 2.1.1 Specification
  url: https://github.com/ocpi/ocpi
servers:
  - url: https://example.com/ocpi/2.1.1
    description: Example OCPI server
security:
  - TokenAuth: []
paths:
  /cdrs:
    get:
      operationId: getCdrs
      summary: Get CDRs List (CPO Interface)
      description: Fetch CDR objects from the CPO, last updated between date_from and
        date_to (paginated).
      tags:
        - CDRs - CPO Interface
      parameters:
        - $ref: ./shared/parameters.yaml#/components/parameters/date_from
        - $ref: ./shared/parameters.yaml#/components/parameters/date_to
        - $ref: ./shared/parameters.yaml#/components/parameters/offset
        - $ref: ./shared/parameters.yaml#/components/parameters/limit
      responses:
        "200":
          description: List of CDR objects.
          headers:
            X-Total-Count:
              $ref: ./shared/headers.yaml#/components/headers/X-Total-Count
            X-Limit:
              $ref: ./shared/headers.yaml#/components/headers/X-Limit
            Link:
              $ref: ./shared/headers.yaml#/components/headers/Link
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CDRListResponse"
        "401":
          description: Unauthorized.
    post:
      operationId: postReceiverCdr
      summary: Create CDR (eMSP Interface)
      description: Create a new CDR in the eMSP's system. The response SHALL contain a
        Location header with the URL to the newly created CDR.
      tags:
        - CDRs - eMSP Interface
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CDR"
      responses:
        "201":
          description: CDR created. Location header contains URL to the new CDR.
          headers:
            Location:
              description: URL to the newly created CDR object.
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: ./shared/common.yaml#/components/schemas/OcpiResponse
        "401":
          description: Unauthorized.
  /cdrs/{cdr_id}:
    get:
      operationId: getReceiverCdr
      summary: Get CDR (eMSP Interface)
      description: Retrieve an existing CDR from the eMSP's system. The URL is
        provided by the eMSP in the Location header of the POST response.
      tags:
        - CDRs - eMSP Interface
      parameters:
        - name: cdr_id
          in: path
          required: true
          description: ID of the CDR (as returned in the Location header).
          schema:
            type: string
      responses:
        "200":
          description: The requested CDR object.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CDRResponse"
        "401":
          description: Unauthorized.
        "404":
          description: CDR not found.
components:
  securitySchemes:
    TokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: OCPI credentials token passed in the Authorization header.
  schemas:
    CDRResponse:
      type: object
      required:
        - status_code
        - timestamp
        - data
      properties:
        data:
          $ref: "#/components/schemas/CDR"
        status_code:
          type: integer
          description: OCPI status code (1xxx=success, 2xxx=client error, 3xxx=server
            error, 4xxx=hub error).
          example: 1000
        status_message:
          type: string
          description: An optional status message which may help when debugging.
        timestamp:
          $ref: ./shared/schemas/types.yaml#/components/schemas/DateTime
      additionalProperties: true
    CDRListResponse:
      type: object
      required:
        - status_code
        - timestamp
        - data
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/CDR"
        status_code:
          type: integer
          description: OCPI status code (1xxx=success, 2xxx=client error, 3xxx=server
            error, 4xxx=hub error).
          example: 1000
        status_message:
          type: string
          description: An optional status message which may help when debugging.
        timestamp:
          $ref: ./shared/schemas/types.yaml#/components/schemas/DateTime
      additionalProperties: true
    CDR:
      type: object
      description: A Charge Detail Record is the description of a concluded charging
        session. CDRs are immutable once sent; use Credit CDRs for corrections.
      required:
        - country_code
        - party_id
        - id
        - start_date_time
        - end_date_time
        - cdr_token
        - auth_method
        - cdr_location
        - currency
        - charging_periods
        - total_cost
        - total_energy
        - total_time
        - last_updated
      properties:
        country_code:
          type: string
          maxLength: 2
          description: ISO-3166 alpha-2 country code of the CPO.
        party_id:
          type: string
          maxLength: 3
          description: ID of the CPO.
        id:
          type: string
          maxLength: 39
          description: Unique ID of the CDR per country_code/party_id combination.
        start_date_time:
          $ref: ./shared/schemas/types.yaml#/components/schemas/DateTime
        end_date_time:
          $ref: ./shared/schemas/types.yaml#/components/schemas/DateTime
        session_id:
          type: string
          maxLength: 36
          description: Unique ID of the Session for which this CDR is sent.
        cdr_token:
          $ref: ./shared/schemas/cdrs.yaml#/components/schemas/CdrToken
        auth_method:
          $ref: ./shared/schemas/cdrs.yaml#/components/schemas/AuthMethod
        authorization_reference:
          type: string
          maxLength: 36
          description: Reference to the authorization given by the eMSP.
        cdr_location:
          $ref: ./shared/schemas/cdrs.yaml#/components/schemas/CdrLocation
        meter_id:
          type: string
          maxLength: 255
          description: Identification of the Meter inside the Charge Point.
        currency:
          type: string
          maxLength: 3
          description: ISO-4217 code of the currency.
        tariffs:
          type: array
          items:
            $ref: ./tariffs.yaml#/components/schemas/Tariff
          description: List of relevant Tariffs.
        charging_periods:
          type: array
          minItems: 1
          items:
            $ref: ./shared/schemas/cdrs.yaml#/components/schemas/ChargingPeriod
          description: List of Charging Periods that make up this charging session.
        signed_data:
          $ref: ./shared/schemas/cdrs.yaml#/components/schemas/SignedData
        total_cost:
          $ref: ./shared/schemas/types.yaml#/components/schemas/Price
        total_fixed_cost:
          $ref: ./shared/schemas/types.yaml#/components/schemas/Price
        total_energy:
          type: number
          description: Total energy charged in kWh.
        total_energy_cost:
          $ref: ./shared/schemas/types.yaml#/components/schemas/Price
        total_time:
          type: number
          description: Total duration of the charging session in hours.
        total_time_cost:
          $ref: ./shared/schemas/types.yaml#/components/schemas/Price
        total_parking_time:
          type: number
          description: Total duration of not charging in hours.
        total_parking_cost:
          $ref: ./shared/schemas/types.yaml#/components/schemas/Price
        total_reservation_cost:
          $ref: ./shared/schemas/types.yaml#/components/schemas/Price
        remark:
          type: string
          maxLength: 255
          description: Optional remark with additional information.
        invoice_reference_id:
          type: string
          maxLength: 39
          description: Reference to an invoice for this CDR.
        credit:
          type: boolean
          description: When true, this is a Credit CDR correcting a previous CDR.
        credit_reference_id:
          type: string
          maxLength: 39
          description: ID of the CDR that this Credit CDR corrects.
        home_charging_compensation:
          type: boolean
          description: When true, this CDR is for a home charger session with financial
            compensation.
        last_updated:
          $ref: ./shared/schemas/types.yaml#/components/schemas/DateTime
      additionalProperties: true
