openapi: 3.1.0
info:
  title: OCPI 2.1.1 - Commands
  description: The Commands module enables remote commands from eMSP to CPO, such
    as starting/stopping sessions, reservations, and unlocking connectors. Uses
    async callbacks via response_url.
  version: 2.1.1
  license:
    name: Creative Commons Attribution-NoDerivatives 4.0 International
    url: https://creativecommons.org/licenses/by-nd/4.0/
externalDocs:
  description: OCPI 2.1.1 Specification
  url: https://github.com/ocpi/ocpi
servers:
  - url: https://example.com/ocpi/2.1.1
    description: Example OCPI server
security:
  - TokenAuth: []
paths:
  /commands/RESERVE_NOW:
    post:
      operationId: postReserveNow
      summary: Reserve Now (CPO Interface)
      description: Request the Charge Point to reserve an EVSE for a Token.
      tags:
        - Commands - CPO Interface
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReserveNow"
      responses:
        "200":
          description: Command request accepted by CPO.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CommandEnvelopeResponse"
        "401":
          description: Unauthorized.
      callbacks:
        commandResult:
          "{$request.body#/response_url}":
            post:
              summary: Async result from Charge Point
              security:
                - TokenAuth: []
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/CommandResponse"
              responses:
                "200":
                  description: Result received.
                  content:
                    application/json:
                      schema:
                        $ref: ./shared/common.yaml#/components/schemas/OcpiResponse
                "400":
                  description: Invalid callback payload.
  /commands/START_SESSION:
    post:
      operationId: postStartSession
      summary: Start Session (CPO Interface)
      description: Request the Charge Point to start a transaction on the given EVSE/Connector.
      tags:
        - Commands - CPO Interface
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StartSession"
      responses:
        "200":
          description: Command request accepted by CPO.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CommandEnvelopeResponse"
        "401":
          description: Unauthorized.
      callbacks:
        commandResult:
          "{$request.body#/response_url}":
            post:
              summary: Async result from Charge Point
              security:
                - TokenAuth: []
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/CommandResponse"
              responses:
                "200":
                  description: Result received.
                  content:
                    application/json:
                      schema:
                        $ref: ./shared/common.yaml#/components/schemas/OcpiResponse
                "400":
                  description: Invalid callback payload.
  /commands/STOP_SESSION:
    post:
      operationId: postStopSession
      summary: Stop Session (CPO Interface)
      description: Request the Charge Point to stop an ongoing session.
      tags:
        - Commands - CPO Interface
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StopSession"
      responses:
        "200":
          description: Command request accepted by CPO.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CommandEnvelopeResponse"
        "401":
          description: Unauthorized.
      callbacks:
        commandResult:
          "{$request.body#/response_url}":
            post:
              summary: Async result from Charge Point
              security:
                - TokenAuth: []
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/CommandResponse"
              responses:
                "200":
                  description: Result received.
                  content:
                    application/json:
                      schema:
                        $ref: ./shared/common.yaml#/components/schemas/OcpiResponse
                "400":
                  description: Invalid callback payload.
  /commands/UNLOCK_CONNECTOR:
    post:
      operationId: postUnlockConnector
      summary: Unlock Connector (CPO Interface)
      description: Request the Charge Point to unlock the connector. This functionality
        is for help desk operators only.
      tags:
        - Commands - CPO Interface
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UnlockConnector"
      responses:
        "200":
          description: Command request accepted by CPO.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CommandEnvelopeResponse"
        "401":
          description: Unauthorized.
      callbacks:
        commandResult:
          "{$request.body#/response_url}":
            post:
              summary: Async result from Charge Point
              security:
                - TokenAuth: []
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/CommandResponse"
              responses:
                "200":
                  description: Result received.
                  content:
                    application/json:
                      schema:
                        $ref: ./shared/common.yaml#/components/schemas/OcpiResponse
                "400":
                  description: Invalid callback payload.
webhooks:
  commandResult:
    post:
      operationId: postCommandResult
      summary: Receive async CommandResult (eMSP Interface)
      description: The eMSP interface implements this webhook to receive the
        async CommandResult from the CPO via POST to the response_url provided
        in the original command request.
      tags:
        - Commands - eMSP Interface
      security:
        - TokenAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommandResponse"
      responses:
        "200":
          description: Result received.
          content:
            application/json:
              schema:
                $ref: ./shared/common.yaml#/components/schemas/OcpiResponse
components:
  securitySchemes:
    TokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: OCPI credentials token passed in the Authorization header.
  schemas:
    CommandEnvelopeResponse:
      type: object
      required:
        - status_code
        - timestamp
        - data
      properties:
        data:
          $ref: "#/components/schemas/CommandResponse"
        status_code:
          type: integer
          description: OCPI status code (1xxx=success, 2xxx=client error, 3xxx=server
            error, 4xxx=hub error).
          example: 1000
        status_message:
          type: string
          description: An optional status message which may help when debugging.
        timestamp:
          $ref: ./shared/schemas/types.yaml#/components/schemas/DateTime
      additionalProperties: true
    ReserveNow:
      type: object
      description: Request to reserve an EVSE for a Token.
      required:
        - response_url
        - token
        - expiry_date
        - reservation_id
        - location_id
      properties:
        response_url:
          type: string
          format: uri
          maxLength: 255
          description: URL that the CommandResult POST should be sent to.
        token:
          $ref: ./tokens.yaml#/components/schemas/Token
        expiry_date:
          $ref: ./shared/schemas/types.yaml#/components/schemas/DateTime
        reservation_id:
          type: string
          maxLength: 36
          description: Unique reservation ID.
        location_id:
          type: string
          maxLength: 36
          description: Location.id of the Location to reserve at.
        evse_uid:
          type: string
          maxLength: 36
          description: Optional EVSE.uid of the specific EVSE to reserve.
        authorization_reference:
          type: string
          maxLength: 36
          description: Reference to the authorization given by the eMSP.
      additionalProperties: true
    StartSession:
      type: object
      description: Request to start a charging session.
      required:
        - response_url
        - token
        - location_id
      properties:
        response_url:
          type: string
          format: uri
          maxLength: 255
          description: URL that the CommandResult POST should be sent to.
        token:
          $ref: ./tokens.yaml#/components/schemas/Token
        location_id:
          type: string
          maxLength: 36
          description: Location.id of the Location to start charging at.
        evse_uid:
          type: string
          maxLength: 36
          description: Optional EVSE.uid. Required when connector_id is set.
        connector_id:
          type: string
          maxLength: 36
          description: Optional Connector.id. Required when
            START_SESSION_CONNECTOR_REQUIRED capability is set.
        authorization_reference:
          type: string
          maxLength: 36
          description: Reference to the authorization given by the eMSP.
      additionalProperties: true
    StopSession:
      type: object
      description: Request to stop an ongoing charging session.
      required:
        - response_url
        - session_id
      properties:
        response_url:
          type: string
          format: uri
          maxLength: 255
          description: URL that the CommandResult POST should be sent to.
        session_id:
          type: string
          maxLength: 36
          description: Session.id of the Session to stop.
      additionalProperties: true
    UnlockConnector:
      type: object
      description: Request to unlock a connector (for help desk operators).
      required:
        - response_url
        - location_id
        - evse_uid
        - connector_id
      properties:
        response_url:
          type: string
          format: uri
          maxLength: 255
          description: URL that the CommandResult POST should be sent to.
        location_id:
          type: string
          maxLength: 36
          description: Location.id of the Location.
        evse_uid:
          type: string
          maxLength: 36
          description: EVSE.uid of the EVSE.
        connector_id:
          type: string
          maxLength: 36
          description: Connector.id of the Connector to unlock.
      additionalProperties: true
    CommandResponse:
      type: object
      description: Immediate response from CPO indicating whether the command was
        understood and forwarded (not the result from the Charge Point itself).
      required:
        - result
      properties:
        result:
          $ref: "#/components/schemas/CommandResponseType"
        message:
          type: array
          items:
            $ref: ./shared/schemas/types.yaml#/components/schemas/DisplayText
          description: Human-readable description of the result.
      additionalProperties: true
    CommandResponseType:
      anyOf:
        - type: string
          enum:
            - NOT_SUPPORTED
            - REJECTED
            - ACCEPTED
            - TIMEOUT
            - UNKNOWN_SESSION
        - type: string
      description: Result of the command request.
